services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_CONF: ${APACHE_CONF}
        APP_ENV: ${APP_ENV}
    container_name: videgrenier-web-dev
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db-dev
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

  db-dev:
    image: mysql:8
    container_name: videgrenier-db-dev
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: ${MYSQL_AUTHENTICATION_PLUGIN}
    volumes:
      - db_data_dev:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql

volumes:
  db_data_dev:
