
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_CONF: ${APACHE_CONF}
        APP_ENV: ${APP_ENV}
    container_name: videgrenier-web-dev
    ports:
      - "${APP_PORT}:${CONTAINER_APP_PORT}"
    volumes:
      - .:/var/www/html
    depends_on:
      - db-dev
    env_file: .env.dev

  db-dev:
    image: mysql:8
    container_name: videgrenier-db-dev
    restart: always
    ports:
      - "${DB_PORT}:${CONTAINER_DB_PORT}"
    environment:
      MYSQL_AUTHENTICATION_PLUGIN: ${MYSQL_AUTHENTICATION_PLUGIN}
    volumes:
      - db_data_dev:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    env_file: .env.dev

volumes:
  db_data_dev:
