# Workflow: Build de l'image Docker de développement
# Ce workflow se déclenche lors d'un push sur la branche 'develop'.
# Il est responsable de la reconstruction de l'image Docker de développement.

name: Build Dev Docker Image on Push to Develop

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop # Se déclenche pour les PR ciblant la branche 'develop'

jobs:
  build-dev-image:
    runs-on: ubuntu-latest # Exécute le job sur une machine virtuelle Ubuntu

    steps:
      - name: Checkout repository # Étape pour cloner le dépôt Git
        uses: actions/checkout@v4

      - name: Set up Docker Buildx # Configure Docker Buildx pour des builds performants
        uses: docker/setup-buildx-action@v3

      - name: Build Dev Docker Image # Reconstruit l'image Docker du service web-dev
        run: docker build -f Dockerfile -t bloc5-web-dev:latest --build-arg APACHE_CONF=dev.conf .