name: Build Dev Docker Image on Push to Develop

on:
  push:
    branches:
      - main

jobs:
  build-dev-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Dev Docker Image
        run: docker-compose -f docker-compose.dev.yaml build web-dev
