# Workflow: Build de l'image Docker de développement
# Ce workflow se déclenche lors d'un push sur la branche 'develop'.
# Il est responsable de la reconstruction de l'image Docker de développement.

name: Build Dev Docker Image on Push to Develop

on:
  push:
    branches:
      - develop # Se déclenche lors d'un push sur la branche 'develop'

jobs:
  build-dev-image:
    runs-on: ubuntu-latest # Exécute le job sur une machine virtuelle Ubuntu

    steps:
      - name: Checkout repository # Étape pour cloner le dépôt Git
        uses: actions/checkout@v4

      - name: Build Dev Docker Image # Reconstruit l'image Docker du service web-dev
        run: docker-compose -f docker-compose.dev.yaml build web-dev