
name: CD - Deploy Prod Image to Registry (on main merge)

on:
  push:
    branches:
      - main 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_ENV_PROD: prod
  APACHE_CONF_PROD: prod.conf

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Build and Push Prod Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest # Toujours le dernier build sur main
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} # Tag avec le SHA complet du commit
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}
          build-args: |
            APP_ENV=${{ env.APP_ENV_PROD }}
            APACHE_CONF=${{ env.APACHE_CONF_PROD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Image Build and Push Complete"
        run: |
          echo "Prod container image has been successfully built and pushed to the registry."
          echo "--- Image Tags ---"
          echo "  - Latest: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          echo "  - Commit SHA: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "  - Build Number: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-${{ github.run_number }}"
          echo "  - Versioned: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}"