
name: CD - Deploy Prod Image (on Main PR) 

on:
  pull_request:
    types: [opened, synchronize, reopened] 
    branches:
      - main 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_ENV_PROD: prod
  APACHE_CONF_PROD: prod.conf

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construire et pousser l'image Docker de production finale avec des tags multiples
      - name: Build and Push Prod Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-main-${{ github.event.pull_request.number }} 
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} 
          build-args: |
            APP_ENV=${{ env.APP_ENV_PROD }}
            APACHE_CONF=${{ env.APACHE_CONF_PROD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Image Build and Push Complete for Main PR"
        run: |
          echo "L'image Docker pour la PR vers main a été construite et poussée avec succès."
          echo "--- Tags de l'image ---"
          echo "  - Spécifique à la PR: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-main-${{ github.event.pull_request.number }}"
          echo "  - Basé sur le SHA du commit: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"